# Base de datos PostgreSQL (Azure)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# MongoDB (fotos de jugadores)
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}

# JWT Configuration (Production)
security.jwt.secret=${SECURITY_JWT_SECRET}

# Swagger UI deshabilitado en produccion
springdoc.swagger-ui.enabled=false
springdoc.api-docs.enabled=false

# Identity service
identity.service.url=${IDENTITY_SERVICE_URL}