# Nombre de la aplicacion
spring.application.name=DOSW-TechCup-users

#  JPA
spring.jpa.open-in-view=false

#  Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html

# JWT shared secret (same value used by the identity service)
security.jwt.secret=bWktY2xhdmUtc3VwZXItc2VjcmV0YS1wYXJhLWp3dC0xMjM0NTY3ODkwMTIzNDU2