package edu.dosw.users.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.time.LocalDateTime;

/**
 * JPA entity representing an audit log entry in the relational database.
 *
 * <p>Mapped to the {@code audit_logs} table. The
 * {@code chk_audit_log_has_reference} constraint enforces at database level
 * that at least one of the relationships ({@code sportProfile} or
 * {@code invitation}) is non-null, ensuring traceability of every audited
 * event.</p>
 *
 * @see edu.dosw.users.model.AuditLogModel
 * @see edu.dosw.users.mapper.AuditLogMapper
 */
@Entity
@Table(
    name = "audit_logs",
    check = @CheckConstraint(
        name = "chk_audit_log_has_reference",
        constraint = "sport_profile_id IS NOT NULL OR invitation_id IS NOT NULL"
    )
)
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class AuditLogEntity {

    /** Unique identifier automatically generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Audited action type stored as a {@code String} (e.g. {@code "CREATE"}). */
    @Column(name = "action", nullable = false)
    private String action;

    /** Exact date and time when the audited event occurred. */
    @Column(name = "action_timestamp", nullable = false)
    private LocalDateTime timestamp;

    /** Additional description or context of the audited event. */
    @Column(name = "details", columnDefinition = "TEXT")
    private String details;

    /** Sport profile related to the event; may be {@code null} if the event concerns an invitation. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "sport_profile_id")
    private SportProfileEntity sportProfile;

    /** Invitation related to the event; may be {@code null} if the event concerns a sport profile. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "invitation_id")
    private InvitationEntity invitation;
}