package edu.dosw.users.entity;

import java.time.LocalDateTime;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * JPA entity representing a team invitation in the relational database.
 *
 * <p>Mapped to the {@code invitations} table. Records which player received
 * the invitation, which team it belongs to, the invitation status, and the
 * sent and response timestamps.</p>
 *
 * @see edu.dosw.users.model.InvitationModel
 * @see edu.dosw.users.mapper.InvitationMapper
 */
@Entity
@Table(name = "invitations",
    uniqueConstraints = @UniqueConstraint(
        name = "uk_invitations_player_team",
        columnNames = {"player_id", "team_id"}))
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class InvitationEntity {

    /** Unique identifier automatically generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Identifier of the team extending the invitation (external reference). */
    @Column(name = "team_id", nullable = false)
    private Long teamId;

    /** Invitation status stored as a {@code String} (e.g. {@code "PENDING"}). */
    @Column(name = "status", nullable = false)
    private String status;

    /** Date and time when the invitation was sent to the player. */
    @Column(name = "sent_at")
    private LocalDateTime sentAt;

    /** Date and time when the player or captain responded to the invitation. */
    @Column(name = "responded_at")
    private LocalDateTime respondedAt;

    /** Player who receives the invitation. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "player_id", nullable = false)
    private UserEntity player;
}