package edu.dosw.users.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDateTime;

/**
 * JPA entity representing a player's sport profile.
 *
 * <p>Mapped to the {@code sport_profiles} table. Holds a {@code OneToOne}
 * relationship with {@link UserEntity} through the {@code user_id}
 * column. The {@code photoId} field stores the {@code ObjectId} of the
 * {@code PlayerPhoto} document in MongoDB.</p>
 *
 * @see edu.dosw.users.model.SportProfileModel
 * @see edu.dosw.users.mapper.SportProfileMapper
 */
@Entity
@Table(name = "sport_profiles")
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class SportProfileEntity {

    /** Unique identifier automatically generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Player's tactical position stored as a {@code String} (e.g. {@code "GOALKEEPER"}). */
    @Column(name = "position", nullable = false)
    private String position;

    /** Player's jersey number. */
    @Column(name = "dorsal_number")
    private Integer dorsalNumber;

    /** ObjectId of the photo document in MongoDB (24 hexadecimal characters). */
    @Column(name = "photo_id", length = 24)
    private String photoId;

    /** Indicates whether the player is available to participate in tournaments. */
    @Column(name = "available", nullable = false)
    private boolean available;

    /** Date and time when the sport profile was created. */
    @Column(name = "created_at")
    private LocalDateTime createdAt;

    /** Date and time of the last update to the sport profile. */
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    /** User profile that owns this sport profile. */
    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false, unique = true)
    private UserEntity user;
}