package edu.dosw.users.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * JPA entity representing the user profile in the relational database.
 *
 * <p>Mapped to the {@code user_profiles} table. The {@code email} and
 * {@code password} fields are managed by the identity service; this entity
 * stores them as a reference copy for internal queries within the users
 * microservice.</p>
 *
 * @see edu.dosw.users.model.UserProfileModel
 * @see edu.dosw.users.mapper.UserProfileMapper
 */
@Entity
@Table(name = "user_profiles")
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class UserProfileEntity {

    /** Unique identifier automatically generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Full name of the user. */
    @Column(name = "full_name", nullable = false)
    private String fullName;

    /** Unique email address of the user. */
    @Column(name = "email", nullable = false, unique = true)
    private String email;

    /** Hashed password; managed by the identity service. */
    @Column(name = "password", nullable = false)
    private String password;

    /** Unique official identification number of the user. */
    @Column(name = "identification", nullable = false, unique = true)
    private String identification;

    /** Date of birth of the user. */
    @Column(name = "birth_date")
    private LocalDate birthDate;

    /** Gender stored as a {@code String} (e.g. {@code "MALE"}, {@code "FEMALE"}). */
    @Column(name = "gender")
    private String gender;

    /** Institutional relationship stored as a {@code String} (e.g. {@code "STUDENT"}). */
    @Column(name = "school_relation")
    private String schoolRelation;

    /** Name of the academic programme in which the user is enrolled. */
    @Column(name = "academic_program")
    private String academicProgram;

    /** Current academic semester of the user. */
    @Column(name = "semester")
    private Integer semester;

    /** Profile status (e.g. {@code "ACTIVE"}, {@code "INACTIVE"}). */
    @Column(name = "status")
    private String status;

    /** Date and time when the profile was created. */
    @Column(name = "profile_created_at")
    private LocalDateTime profileCreatedAt;

    /** Date and time of the last profile update. */
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    /**
     * Sport profile associated with this user. The relationship is optional;
     * a user can exist without a sport profile.
     */
    @OneToOne(mappedBy = "userProfile", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    private SportProfileEntity sportProfile;
}