package edu.dosw.users.model;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDateTime;

/**
 * MongoDB document that stores a player's photograph.
 *
 * <p>Persisted in the {@code player_photos} collection on MongoDB Atlas.
 * The {@link #id} field generated by MongoDB is the value stored in
 * {@code SportProfileEntity#photoId}, acting as a cross-reference between
 * the relational database and the document store.</p>
 */
@Document(collection = "player_photos")
@Getter
@Setter
@NoArgsConstructor
public class PlayerPhoto {

    /** Unique document identifier in MongoDB (ObjectId as a String). */
    @Id
    private String id;

    /** Identifier of the sport profile that owns this photograph. */
    private Long sportProfileId;

    /** MIME type of the image (e.g. {@code "image/jpeg"}, {@code "image/png"}). */
    private String contentType;

    /** Binary content of the image. */
    private byte[] data;

    /** Date and time when the photograph was uploaded. */
    private LocalDateTime uploadedAt;
}